### ISSUE TITLE
"pecan serve" fails on newly created skeleton project

### ISSUE THREAD

**Issue by hozn** [pecan/pecan#36]
There appears to be an issue where sys.path does not include the current dir ("").

Here are reproduce steps:
```
shell$ cd ~/workspace
shell$ mkdir pecantest && cd pecantest/
shell$  virtualenv /env
shell$ source env/bin/activate
(env) shell$ pip install pecan
(env) shell$ pecan create test_proj
(env) shell$ cd test_proj/
(env) shell$ pecan serve config.py 
```
Exception:
```
(env)hans@fliptux:~/workspace/pecantest/test_proj$ pecan serve config.py 
Traceback (most recent call last):
  File "/home/hans/workspace/pecantest/env/bin/pecan", line 11, in <module>
    sys.exit(CommandRunner.handle_command_line())
  File "/home/hans/workspace/pecantest/env/local/lib/python2.7/site-packages/pecan/commands/base.py", line 96, in handle_command_line
    runner.run(sys.argv[1:])
  File "/home/hans/workspace/pecantest/env/local/lib/python2.7/site-packages/pecan/commands/base.py", line 91, in run
    self.commands[ns.command_name]().run(ns)
  File "/home/hans/workspace/pecantest/env/local/lib/python2.7/site-packages/pecan/commands/serve.py", line 38, in run
    app = self.load_app()
  File "/home/hans/workspace/pecantest/env/local/lib/python2.7/site-packages/pecan/commands/base.py", line 162, in load_app
    return load_app(self.args.config_file)
  File "/home/hans/workspace/pecantest/env/local/lib/python2.7/site-packages/pecan/core.py", line 219, in load_app
    module = __import__(package_name, fromlist=['app'])
```

But I can import the expected module just fine from commandline directly:
```
(env) shell$ python -c "__import__('test_proj', fromlist=['app'])"
# (no exception)
```

I'm sure I'm missing something obvious here.  I haven't dug in through the commandline runner to figure out why sys.path is different.

**Comment by hozn** [comment]
Indeed, in my example I forgot to run "python setup.py develop".  Apologies!
