### ISSUE TITLE
API hangs when request body is not sent with PUT/POST/PATCH

### ISSUE THREAD

**Issue by jasondunsmore** [pecan/pecan#87]
The API hangs when an API is defined without a request body and then request body is not sent with PUT/POST/PATCH request.

Minimal example:

```
import pecan
from pecan import rest

class VersionController(rest.RestController):
    @pecan.expose('json')
    def get(self):
        return {"version": "1.0.0"}

    @pecan.expose('json', int)
    def put(self, foo):
        #return "foo"  # positive control
        return pecan.request.body

    @pecan.expose('json', int)
    def post(self, foo):
        #return "foo"  # positive control
        return pecan.request.body

    @pecan.expose('json', int)
    def patch(self, foo):
        #return "foo"  # positive control
        return pecan.request.body
```

Curl commands to reproduce API hanging:

```
$ curl -X PUT http://127.0.0.1:8080/v1/1
(hangs...)
$ curl -X POST http://127.0.0.1:8080/v1/1
(hangs...)
$ curl -X PATCH http://127.0.0.1:8080/v1/1
(hangs...)
```

When "-d '{}'" is added, the API responds:

```
$ curl -X POST http://127.0.0.1:8080/v1/1 -d '{}'
"{}"
$ curl -X PUT http://127.0.0.1:8080/v1/1 -d '{}'
"{}"
$ curl -X PATCH http://127.0.0.1:8080/v1/1 -d '{}'
"{}"
```

Here is the traceback from when Control-C is typed in the "pecan serve" process while the API is hanging:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/middleware/static.py", line 150, in __call__
    return self.app(environ, start_response)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/middleware/debug.py", line 78, in __call__
    return self.app(environ, start_response)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/middleware/recursive.py", line 56, in __call__
    return self.application(environ, start_response)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/middleware/errordocument.py", line 75, in __call__
    app_iter = self.app(environ, replacement_start_response)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/core.py", line 840, in __call__
    return super(Pecan, self).__call__(environ, start_response)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/core.py", line 683, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/core.py", line 574, in invoke_controller
    result = controller(*args, **kwargs)
  File "/home/jason/repo/experimental/python/test-pecan-patch/pecanrest/pecanrest/controllers/v1.py", line 22, in post
    return pecan.request.body
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/core.py", line 77, in __getattr__
    return getattr(obj, attr)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/pecan/core.py", line 52, in __getattribute__
    return WebObRequest.__getattribute__(self, name)
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/webob/request.py", line 700, in _body__get
    self.make_body_seekable() # we need this to have content_length
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/webob/request.py", line 942, in make_body_seekable
    self.copy_body()
  File "/home/jason/github/magnum/.venv/local/lib/python2.7/site-packages/webob/request.py", line 958, in copy_body
    self.body = self.body_file_raw.read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
KeyboardInterrupt
```

**Comment by jasondunsmore** [comment]
It's an upstream bug  https://github.com/Pylons/webob/issues/233
